# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5154a0b40dfc4083a50b32da0755d487f99946e6c02f20d55d60483c375c72c1d3e77ab7d62df53810681cd5205a4ca8449a29e48d4ccfcf439a9b0304387b95
  MY_CONNECT_EMAIL: 123456

test:
  secret_key_base: e9ff3368e7c87fa5ed0d374506b09b4ece2537ac7f11488c9ffa53caf53e1325ddd0c8f2849a1498d1c37fa4f63f424d3af67d83c440d0c2e2318ad2efe6152e

# Do not keep production secrets in the repository,
# instead read values from the environment.
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
